-- Create expenses table
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    description VARCHAR(500),
    expense_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    expense_category_id BIGINT NOT NULL,
    currency_id BIGINT NOT NULL,
    receipt_url VARCHAR(1000),
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'APPROVED_BY_MANAGER', 'APPROVED_BY_FINANCE', 'REJECTED', 'REQUIRES_REVISION')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_expenses_expense_category FOREIGN KEY (expense_category_id) REFERENCES expense_categories(id),
    CONSTRAINT fk_expenses_currency FOREIGN KEY (currency_id) REFERENCES currencies(id)
);

-- Create indexes for efficient querying
CREATE INDEX idx_expenses_user_category_date ON expenses(user_id, expense_category_id, expense_date);
CREATE INDEX idx_expenses_status ON expenses(status);
CREATE INDEX idx_expenses_date ON expenses(expense_date);

-- Create audit table for expenses
CREATE TABLE expenses_AUD (
    id BIGINT NOT NULL,
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    amount DECIMAL(15,2),
    description VARCHAR(500),
    expense_date DATE,
    user_id BIGINT,
    expense_category_id BIGINT,
    currency_id BIGINT,
    receipt_url VARCHAR(1000),
    status VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id, REV),
    FOREIGN KEY (REV) REFERENCES REVINFO(REV)
);
