CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    daily_budget DECIMAL(15,2) CHECK (daily_budget >= 0),
    monthly_budget DECIMAL(15,2) NOT NULL CHECK (monthly_budget >= 0),
    currency VARCHAR(3) NOT NULL,
    PRIMARY KEY (id)
);
