ALTER TABLE users
ADD COLUMN name VARCHAR(255) NOT NULL,
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN manager_id BIGINT;

ALTER TABLE users
ADD CONSTRAINT fk_users_manager
FOREIGN KEY (manager_id)
REFERENCES users(id);
