CREATE TABLE expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    daily_budget DECIMAL(15,2) NOT NULL CHECK (daily_budget >= 0),
    monthly_budget DECIMAL(15,2) NOT NULL CHECK (monthly_budget >= 0),
    PRIMARY KEY (id),
    CONSTRAINT uk_expense_categories_name UNIQUE (name)
);
