-- Create currencies table
CREATE TABLE currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(3) NOT NULL,
    exchange_rate DECIMAL(15,6) NOT NULL CHECK (exchange_rate > 0),
    PRIMARY KEY (id),
    CONSTRAINT uk_currencies_name UNIQUE (name)
);

-- Create audit table for currencies
CREATE TABLE currencies_AUD (
    id BIGINT NOT NULL,
    REV INTEGER NOT NULL,
    REVTYPE SMALLINT,
    name VARCHAR(3),
    exchange_rate DECIMAL(15,6),
    PRIMARY KEY (id, REV),
    FOREIGN KEY (REV) REFERENCES REVINFO(REV)
);
